### ISSUE TITLE
Shebang改为 #!/bin/env node

### ISSUE THREAD

**Issue by Anillc** [rikumi/jsh#1]
用nvm的情况下node的路径不在`/usr/local/bin/node`, 建议改成`#!/bin/env node`

**Comment by LuckyWindsck** [comment]
似乎大多数情况下都是使用 `#!/usr/bin/env`的，所以应该用`#!/usr/bin/env node`

[Why is it better to use “#!/usr/bin/env NAME” instead of “#!/path/to/NAME” as my shebang?
](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my#answer-410599)

[What's the difference of using #!/usr/bin/env or #!/bin/env in shebang?
](https://stackoverflow.com/questions/5549044/whats-the-difference-of-using-usr-bin-env-or-bin-env-in-shebang#answer-5549091)

**Comment by rikumi** [comment]
很遗憾，作为一个 Shell，在被各种终端模拟器（例如 iTerm2、VSCode）启动时，环境变量是空的，更没有 PATH，所以 env 也找不到任何东西，程序会启动失败。

实际上这是个鸡生蛋蛋生鸡的问题，环境变量是 Shell 本身需要从文件中读入的，因此是环境变量依赖 Shell 的执行，所以 Shell 的执行就不能依赖环境变量。

要解决这个问题，不能用 env，可能需要增加一个安装脚本，把安装时的 node 路径记录到一个单独带 Shebang 的入口文件中，然后让该文件去调用 js 入口。

**Comment by rikumi** [comment]
参考：ef208f22

**Comment by Anillc** [comment]
虽然感觉这样实现挺别扭的，但是想了下，也没有想出更好的解决方案了

**Comment by tusooa** [comment]
> 很遗憾，作为一个 Shell，在被各种终端模拟器（例如 iTerm2、VSCode）启动时，环境变量是空的，更没有 PATH，所以 env 也找不到任何东西，程序会启动失败。

一个进程初始的环境变量是从亲进程继承的，除非用 execve() 之类的函数覆盖。我用 Konsole 测试，用env，可以执行。

```
] cat main.js
#!/usr/bin/env node

for (;;) {
  console.log(1);
}
] which node
/home/tusooa/.nvm/versions/node/v12.18.3/bin/node
] konsole -e ./main.js
```

> 实际上这是个鸡生蛋蛋生鸡的问题，环境变量是 Shell 本身需要从文件中读入的，因此是环境变量依赖 Shell 的执行，所以 Shell 的执行就不能依赖环境变量。

环境变量，跟有没有shell，没得关系。init有没有环境变量？当然有。但是init不是shell。

```
] sudo cat /proc/1/environ
SHLVL=1HOME=/OLDPWD=/TERM=linuxintel_iommu=onBOOT_IMAGE=/vmlinuz-5.10.27-gentoo-x86_64pcie_acs_override=downstream,multifunctionPWD=/%
```

**Comment by Anillc** [comment]
突然想起了这个问题，回来说一下。`PATH` 环境变量一般是在 `login` 的时候赋予的（通过执行 `/etc/profile` 等文件），子进程默认会继承环境变量。当用户能够拿到 shell 的时候，其实已经有了 `PATH` 环境变量了。

回到这个问题，我在 issue 中说到的是 `nvm`，但是 `nvm` 并不是将 `PATH` 相关的内容写到的 `/etc/profile`，而是默认使用了 `.bashrc` 这样的文件。如果要解决这个 issue 的话，可以考虑把启动文件写成一个 `sh` 脚本，然后使用 `exec` 来切换到 `node`。

```sh
#!/bin/sh
exec node somewhere/some.js
```

不过我也已经很久没有使用 `nvm` 了。
